### ISSUE TITLE
Command rate limiting not working when going on->off->on->off.....

### ISSUE THREAD

**Issue by ctech4285** [Zubax/opengrab_epm_v3#17]

**Comment by pavel-kirienko** [comment]
I understood that rate limiting is only needed if the goal does not change.

Remove `magnet_is_on` condition from https://github.com/Zubax/opengrab_epm_v3/blob/master/firmware/src/magnet/magnet.cpp#L194 and https://github.com/Zubax/opengrab_epm_v3/blob/master/firmware/src/magnet/magnet.cpp#L213

**Comment by pavel-kirienko** [comment]
Is it fixed now?

**Comment by ctech4285** [comment]
I can see now why you did it this way. Now a user has to wait like 3 seconds before going from turn on -> turn off...
Let me see what I can cock up

**Comment by pavel-kirienko** [comment]
Still relevant?
