### ISSUE TITLE
Test Dipswitch 

### ISSUE THREAD

**Issue by ctech4285** [Zubax/opengrab_epm_v3#20]
Add test dipswitch routine to drwatson

**Comment by ctech4285** [comment]
To keep it simple, how about blink error for 1s on boot when all four dips are low?

**Comment by pavel-kirienko** [comment]
Sketchy. I'll fix drwatson someday to do it right.

**Comment by ctech4285** [comment]
Hmm you don't seem to like simple solutions 

Think of this as the dashboard indicator light check in your car. When you turn the ignition on all indicators light up for a second....

**Comment by pavel-kirienko** [comment]
Okay, makes sense. I thought you were proposing a temporary hack. Will you implement that?
