### ISSUE TITLE
Vin measurement incorrect after boot

### ISSUE THREAD

**Issue by ctech4285** [Zubax/opengrab_epm_v3#22]
make PRODROPPER=1

First time after boot when Vin is measured it returns 5000ish mV instead of 12000ish. ACD pin V is correct at this time at around 1000mV. 

This commit has the syslog print out to reproduce 

https://github.com/Zubax/opengrab_epm_v3/tree/pro_epm

**Comment by pavel-kirienko** [comment]
This is because of averaging: https://github.com/Zubax/opengrab_epm_v3/blob/master/firmware/src/sys/board.cpp#L471.

We can either add initialization of the previous sample on first measurement, or we can remove averaging completely. We probably should remove it, it's wonky.

**Comment by ctech4285** [comment]
Let's leave it in and call getSupplyVoltageInMillivolts a few times after boot? I am worried about introducing sporadic noise

**Comment by pavel-kirienko** [comment]
No, we must not call it multiple times after boot because that creates a leaky abstraction. We can do this, right after `x` is computed:

```c++
if (old_value == 0)  // If old value is uninitialized, the result will be half of the real value
{
    x *= 2;
}
```
