### ISSUE TITLE
Migrate to JST GH

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/opengrab_epm_v3#25]
References:
- http://www.digikey.com/product-detail/en/SM04B-GHS-TB(LF)(SN)%3B-/455-1566-1-ND/807834
- http://uavcan.org/Specification/8._Hardware_design_recommendations/#physical-connector-definition
- https://github.com/PX4/Hardware/issues/18

**Comment by ctech4285** [comment]
This is going into PCB Rev6 then

**Comment by ctech4285** [comment]
Done
