### ISSUE TITLE
ADC seems to hickup every now and then

### ISSUE THREAD

**Issue by ctech4285** [Zubax/opengrab_epm_v3#40]
It seems that it miss read input or output voltage, triggers an error

**Comment by pavel-kirienko** [comment]
Please provide more info; the description you provided is insufficient. How exactly the misreading happens? How frequently? What output is produced and what output is expected? What error is triggered?

**Comment by ctech4285** [comment]
Problem found, external ADC capacitor lags behind the main capacitor voltage. 

https://github.com/Zubax/opengrab_epm_v3/blob/master/firmware/src/magnet/magnet.cpp#L262
